### ISSUE TITLE
Brazil no longer observes DST

### ISSUE THREAD

**Issue by gjdame** [tzinfo/tzinfo#102]
The Brasilia time zone still respects DST. That should no longer be the case. Didn't see any issue raised for this already. Apologies if so.

**Comment by philr** [comment]
TZInfo uses data from the [IANA Time Zone Database](https://www.iana.org/time-zones). The [2019b release](https://mm.icann.org/pipermail/tz-announce/2019-July/000056.html) of the database includes the changes made in Brazil this year to no longer observe DST.

If you are using TZInfo's [`ZoneinfoDataSource`](https://www.rubydoc.info/gems/tzinfo/TZInfo/DataSources/ZoneinfoDataSource), then you will likely need to update your operating system's tzdata package.

If you are using [`RubyDataSource`](https://www.rubydoc.info/gems/tzinfo/TZInfo/DataSources/RubyDataSource), then you will need to update to [version 1.2019.2](https://github.com/tzinfo/tzinfo-data/releases/tag/v1.2019.2) or later of the tzinfo-data gem.

You can find out which data source you are using with [`TZInfo::DataSource.get`](https://www.rubydoc.info/gems/tzinfo/TZInfo%2FDataSource%2Eget).

**Comment by gjdame** [comment]
Awesome! ty
