### ISSUE TITLE
Brazil and daylight savings

### ISSUE THREAD

**Issue by luckyx1** [tzinfo/tzinfo#105]
Now that Brazil is declaring the end of daylight savings, do we need to make any changes to the gem to accommodate this change? https://time.is/time_zone_news/no_dst_in_brazil_in_2019

**Comment by philr** [comment]
Duplicate of #102  

See also #104 if you are using TZInfo 0.3.x.

**Comment by philr** [comment]
See also #104 if you are using TZInfo 0.3.x.

**Comment by luckyx1** [comment]
Thanks so much!
