### ISSUE TITLE
warning: The last argument is used as the keyword parameter

### ISSUE THREAD

**Issue by jasnow** [tzinfo/tzinfo#106]
Ruby 2.7.0-preview2 is issuing the following warning
```
/Users/USER/.rvm/gems/ruby-2.7.0-preview2@ruby2.7-rails6.1/
gems/tzinfo-1.2.5/lib/tzinfo/ruby_core_support.rb:142: 
warning: The last argument is used as the keyword parameter
```

Yes, I know it is a warning, so this is just a heads-up.

**Comment by philr** [comment]
Thanks for the report.

This has now been fixed in commit 54fce8c1f61ba3b891311f7c7befc32a52ea4a30. The fix will be included in a imminent 1.2.6 release.

**Comment by jasnow** [comment]
Thanks for the update. Will add comment here after I verify the new release.

**Comment by jasnow** [comment]
Verified fixed.
