### ISSUE TITLE
Any chance for a v0.37.58 with 2020c in it?

### ISSUE THREAD

**Issue by vosechu** [tzinfo/tzinfo#121]
I was wondering if anyone would be able to make a v0.37.58 that contained 2020b and 2020c? I'm sorry to ask, but I'm stuck on a super old release of Rails and we can't get off of it anytime soon.

If this is a reasonable thing for a new community member to try to take on, I'd be happy to give it a whirl and make a PR? But I completely recognize that often onboarding is harder than just doing the thing :)

Thank you for all your hard work!

**Comment by philr** [comment]
At the moment the [0.3 branch](https://github.com/tzinfo/tzinfo/tree/0.3) is being updated soon after each time zone database release (the 2020c data update is in 15a5b27b5af65de9d37ded58151d9d841623247e).

0.3.x releases are made sporadically when there are significant changes. The Fiji change in 2020c probably qualifies, so you can likely expect a 0.3.58 release soon.

If you don't want to wait for a release, you can use the code from git directly, e.g. with the following in your Gemfile:

```ruby
gem 'tzinfo', git: 'https://github.com/tzinfo/tzinfo.git', branch: '0.3'
```

**Comment by vosechu** [comment]
Amazing! Thank you so, so much!
