### ISSUE TITLE
TZInfo::Timezone.get returns TZInfo::DataTimezone instead of TZInfo::Timezone

### ISSUE THREAD

**Issue by eprislac** [tzinfo/tzinfo#122]
TZInfo::Timezone.get returns TZInfo::DataTimezone instead of TZInfo::Timezone when tzinfo-data is installed.
This means I cannot access a lot of the functionality provided by TZInfo::Timezone.

__ex:__
```ruby
[9] pry(main)> TZInfo::Timezone.get('America/Los_Angeles').base_utc_offset
NoMethodError: undefined method `base_utc_offset' for #<TZInfo::DataTimezone: America/Los_Angeles>
```

__using:__
```ruby
gem 'tzinfo-data', '~> 1.2019.3'
```

**Comment by philr** [comment]
`TZInfo::DataTimezone` is a subclass of `TZInfo::Timezone`.

Which version of the tzinfo gem are you using (tzinfo provides the interface, tzinfo-data supplies time zone data for tzinfo to use)?

The `TZInfo::Timezone#base_utc_offset` method was added in tzinfo version 2.0.0. If you're using tzinfo v1, you'll need the following instead:

```ruby
TZInfo::Timezone.get('America/Los_Angeles').period_for_utc(Time.now.utc).utc_offset
=> -28800
```

**Comment by philr** [comment]
At the moment the `'~> 1.2019.3'` version constraint you have on the tzinfo-data gem will be restricting you to time zone data released in 2019. So far there have been 4 [releases](https://github.com/tzinfo/tzinfo-data/releases) since then.

I'd suggest just removing the version constraint:

```ruby
gem 'tzinfo-data'
```
