### ISSUE TITLE
TimezonePeriod#end_transition returning INT_MAX for some timezones without DST when tzinfo-data is not loaded

### ISSUE THREAD

**Issue by 16Bitt** [tzinfo/tzinfo#125]
Hi there! My team has run into some unexpected behavior in the `America/Caracas` timezone, and we see the same behavior for `America/Sao_Paulo` as well, so I'm guessing it impacts more timezones than we've encountered.

# Versions

* Ruby: 2.5.5
* tzinfo: 2.0.1 (seeing it on older 1.x.x versions as well)
* Platforms (both have an up-to-date tzdata package)
    * void linux 1.0
    *  Ubuntu 18.04.4 LTS

# Reproduction

```ruby
TZInfo::Timezone.get('America/Caracas').current_period.end_transition.at.to_i
# => 2147483647
TZInfo::Timezone.get('America/Sao_Paulo').current_period.end_transition.at.to_i
# => 2147483647
2**31 - 1
# => 2147483647

require 'tzinfo/data'
# => true
TZInfo::Timezone.get('America/Caracas').current_period.end_transition
# => nil
TZInfo::Timezone.get('America/Sao_Paulo').current_period.end_transition
# => nil
```

According to the docs, a `nil` should be returned if the current transition is unbounded, but when using the system provided timezones, we reliably get `INT_MAX` instead.

**Comment by philr** [comment]
In this case tzinfo is just presenting the information from the zoneinfo file. The /usr/share/zoneinfo/America/Caracas file from the Ubuntu tzdata package version 2021a-0ubuntu0.18.04 contains the following contents:

<pre>
     00 01 02 03 04 05 06 07  08 09 0a 0b 0c 0d 0e 0f

000  54 5a 69 66 32 00 00 00  00 00 00 00 00 00 00 00  |TZif2...........|
010  00 00 00 00 00 00 00 04  00 00 00 04 00 00 00 00  |................|
020  00 00 00 06 00 00 00 04  00 00 00 12 80 00 00 00  |................|
030  93 1e 2c 3c f6 98 ec 48  47 5b 92 70 57 25 a9 70  |..,<...HG[.pW%.p|
040  7f ff ff ff 01 02 03 02  03 03 ff ff c1 40 00 00  |.............@..|
050  ff ff c1 44 00 04 ff ff  c0 b8 00 08 ff ff c7 c0  |...D............|
060  00 0e 4c 4d 54 00 43 4d  54 00 2d 30 34 33 30 00  |..LMT.CMT.-0430.|
070  2d 30 34 00 00 00 00 00  00 00 00 00 54 5a 69 66  |-04.........TZif|
080  32 00 00 00 00 00 00 00  00 00 00 00 00 00 00 00  |2...............|
090  00 00 00 04 00 00 00 04  00 00 00 00 <b>00 00 00 07</b>  |................|
0a0  00 00 00 04 00 00 00 12  <b>f8 00 00 00 00 00 00 00</b>  |................|
0b0  <b>ff ff ff ff 69 87 1a 40  ff ff ff ff 93 1e 2c 3c</b>  |....i..@......,<|
0c0  <b>ff ff ff ff f6 98 ec 48  00 00 00 00 47 5b 92 70</b>  |.......H....G[.p|
0d0  <b>00 00 00 00 57 25 a9 70  <i>00 00 00 00 7f ff ff ff</i></b>  |....W%.p........|
0e0  00 01 02 03 02 03 03 ff  ff c1 40 00 00 ff ff c1  |..........@.....|
0f0  44 00 04 ff ff c0 b8 00  08 ff ff c7 c0 00 0e 4c  |D..............L|
100  4d 54 00 43 4d 54 00 2d  30 34 33 30 00 2d 30 34  |MT.CMT.-0430.-04|
110  00 00 00 00 00 00 00 00  00 0a 3c 2d 30 34 3e 34  |..........<-04>4|
120  0a                                                |.|
</pre>

tzinfo uses the second (64-bit) section starting at 0x7c. There are 7 transition times in the file (indicated by the 4 bytes from 0x9c). The transition times are the 7 64-bit integers from 0xa8 to 0xdf. The final transition is `00 00 00 00 7f ff ff ff` (2147483647 in decimal).

I've not checked the Void Linux package, but I expect it is similar.

The latest version of the zoneinfo compiler `zic` produces 'slim' zoneinfo files that omit this final transition by default (as well as the initial transition at -576460752303423488). The Ubuntu package is built an earlier version of `zic` that [includes the transition at 2147483648](https://github.com/eggert/tz/commit/6c0757509cf73ba6e086be9ce145815942ddf486) for compatibility with a [bug in Qt](https://bugreports.qt.io/browse/QTBUG-53071).


If you look at the period starting after the final transition with tzinfo, you'll find it has an unbounded end:

```ruby
TZInfo::Timezone.get('America/Caracas').period_for(Time.at(2147483648)).end_transition
# => nil
```

The extra transition makes no difference to conversions between UTC and local time. If you are interested in the precise times when transitions occur though, I would recommend either using the tzinfo-data gem or building your own 'slim' zoneinfo files from the [IANA Time Zone Database](https://www.iana.org/time-zones).

**Comment by 16Bitt** [comment]
Thank you for the detailed response! My team has a workaround to check for 2147483647, but it sounds like tzinfo-data is probably the better approach long term so that we don't face different behavior across platforms. I'll go ahead and close this out since it sounds like we're using outdated packages.

Thanks again!
