### ISSUE TITLE
TZInfo::DataSourceNotFound for new Rails application (Ruby 3.1.0 on Windows)

### ISSUE THREAD

**Issue by Yashk626** [tzinfo/tzinfo#128]
Hi am facing this issue when creating new rails application ruby, rails are installed correctly but still i am getting tzinfo error 

> Bundle complete! 15 Gemfile dependencies, 70 gems now installed.
> Use `bundle info [gemname]` to see where a bundled gem is installed.
>          run  bundle binstubs bundler
>        rails  importmap:install
> rails aborted!
> TZInfo::DataSourceNotFound: tzinfo-data is not present. Please add gem 'tzinfo-data' to your Gemfile and run bundle install
> 
> C:/Users/nittr/desktop/Ruby/newBlog/config/environment.rb:5:in `<main>'
> 
> Caused by:
> TZInfo::DataSources::ZoneinfoDirectoryNotFound: None of the paths included in TZInfo::DataSources::ZoneinfoDataSource.search_path are valid zoneinfo directories.
> C:/Users/nittr/desktop/Ruby/newBlog/config/environment.rb:5:in `<main>'
> Tasks: TOP => app:template => environment
> (See full trace by running task with --trace)
>        rails  turbo:install stimulus:install
> You must either be running with node (package.json) or importmap-rails (config/importmap.rb) to use this gem.
> You must either be running with node (package.json) or importmap-rails (config/importmap.rb) to use this gem.

This is my gemfile:

```ruby
source "https://rubygems.org"
git_source(:github) { |repo| "https://github.com/#{repo}.git" }

ruby "3.1.0"

# Bundle edge Rails instead: gem "rails", github: "rails/rails", branch: "main"
gem "rails", "~> 7.0.1"

# The original asset pipeline for Rails [https://github.com/rails/sprockets-rails]
gem "sprockets-rails"

# Use sqlite3 as the database for Active Record
gem "sqlite3", "~> 1.4"

# Use the Puma web server [https://github.com/puma/puma]
gem "puma", "~> 5.0"

# Use JavaScript with ESM import maps [https://github.com/rails/importmap-rails]
gem "importmap-rails"

# Hotwire's SPA-like page accelerator [https://turbo.hotwired.dev]
gem "turbo-rails"

# Hotwire's modest JavaScript framework [https://stimulus.hotwired.dev]
gem "stimulus-rails"

# Build JSON APIs with ease [https://github.com/rails/jbuilder]
gem "jbuilder"

# Use Redis adapter to run Action Cable in production
# gem "redis", "~> 4.0"

# Use Kredis to get higher-level data types in Redis [https://github.com/rails/kredis]
# gem "kredis"

# Use Active Model has_secure_password [https://guides.rubyonrails.org/active_model_basics.html#securepassword]
# gem "bcrypt", "~> 3.1.7"

# Windows does not include zoneinfo files, so bundle the tzinfo-data gem
gem "tzinfo-data", platforms: %i[ mingw mswin x64_mingw jruby ]

# Reduces boot times through caching; required in config/boot.rb
gem "bootsnap", require:true

# Use Sass to process CSS
# gem "sassc-rails"

# Use Active Storage variants [https://guides.rubyonrails.org/active_storage_overview.html#transforming-images]
# gem "image_processing", "~> 1.2"

group :development, :test do
  # See https://guides.rubyonrails.org/debugging_rails_applications.html#debugging-with-the-debug-gem
  gem "debug", platforms: %i[ mri mingw x64_mingw ]
end

group :development do
  # Use console on exceptions pages [https://github.com/rails/web-console]
  gem "web-console"

  # Add speed badges [https://github.com/MiniProfiler/rack-mini-profiler]
  # gem "rack-mini-profiler"

  # Speed up commands on slow machines / big apps [https://github.com/rails/spring]
  # gem "spring"
end

group :test do
  # Use system testing [https://guides.rubyonrails.org/testing.html#system-testing]
  gem "capybara"
  gem "selenium-webdriver"
  gem "webdrivers"
end
```

This is my boot file:

```ruby
ENV["BUNDLE_GEMFILE"] ||= File.expand_path("../Gemfile", __dir__)

require "bundler/setup" # Set up gems listed in the Gemfile.
require "bootsnap/setup" # Speed up boot time by caching expensive operations.
```

Can anyone please help me how to resolve this issue.

**Comment by philr** [comment]
It looks like you are using Ruby 3.1.0 on Windows. Rails (ActiveSupport) requires the tzinfo-data gem on Windows to supply time zone data.

Normally, this line in the Gemfile would include tzinfo-data on Windows:

```ruby
gem "tzinfo-data", platforms: %i[ mingw mswin x64_mingw jruby ]
```

It looks like the platform matching isn't working for Ruby 3.1.0 and the gem is not being installed. If you are only running Rails on Windows or are happy to use tzinfo-data for time zone data on all platforms, then you could just remove the `platforms` option from the Gemfile:

```ruby
gem "tzinfo-data"
```

Once you've done this run `bundle install`, which should install the tzinfo-data gem.

**Comment by philr** [comment]
I've opened rubygems/rubygems#5269 for the issue with x64_mingw not matching for Ruby 3.1.0 x64 Windows builds.

**Comment by Yashk626** [comment]
Hi thanks for help. The issue is resolved and server has started successfully. Thanks again for help.
