### ISSUE TITLE
missing tzinfo-data on mac os 12.3 monterey

### ISSUE THREAD

**Issue by mvanh** [tzinfo/tzinfo#131]
tzinfo 1.2.9

I'm getting TZInfo::DataSourceNotFound errors on a newly installed mac 12.3 monterey system using rvm and ruby 2.7.5

`rescue in create_default_data_source': tzinfo-data is not present. Please add gem 'tzinfo-data' to your Gemfile and run bundle install (TZInfo::DataSourceNotFound)`

/usr/share/zoneinfo is present:
testproject % ls -lai /usr/share | grep zo
1152921500312810035 lrwxr-xr-x    1 root  wheel    25 26 Feb 07:05 zoneinfo -> /var/db/timezone/zoneinfo
1152921500312810036 drwxr-xr-x   68 root  wheel  2176 26 Feb 07:05 zoneinfo.default

/etc/localtime is present and pointing to the correct timezone

I thought that tzinfo-data was not necessary on *six systems that had OS level tz databases?

**Comment by mvanh** [comment]
ok - update - it seems i have a /usr/share/zoneinfo and /usr/share/zoneinfo.default directory (for some as yet unknown reason)

The /usr/share/zoneinfo doesn't have a required tab file, but zoneinfo.default does.

`DEFAULT_SEARCH_PATH = ['/usr/share/zoneinfo.default', '/usr/share/zoneinfo', '/usr/share/lib/zoneinfo', '/etc/zoneinfo'].freeze`

and everything is fixed.

trying to work out why

**Comment by mvanh** [comment]
ok - another update.
 
it appears the `validate_zoneinfo_dir` craps out when it can't find an iso3166.tab and never actually looks for a zone.tab (it hits the return nil unless iso3166_tab_path) and the /usr/share/zoneinfo no longer has a iso3166.tab in it (only a zone.tab)

**Comment by philr** [comment]
Both iso3166.tab and zone.tab are required, so returning nil is intentional if either can't be found.

Using /usr/share/zoneinfo.default in preference might be the answer, but I'd like to understand what the difference between that and /usr/share/zoneinfo is and why this has only recently become an issue first. Is this a recent MacOS change, or something unique to your installation?

As a workaround you can skip the detection logic and specify the directory to use with [DataSource.set](https://www.rubydoc.info/gems/tzinfo/TZInfo%2FDataSource%2Eset):

```ruby
TZInfo::DataSource.set(:zoneinfo, '/usr/share/zoneinfo.default')
```

**Comment by philr** [comment]
I've run a test with GitHub Actions on MacOS 12.4 (GitHub virtual environment version 20220710.1).

The test let tzinfo (v1.2.9 and v2.0.4) initialize the data source automatically. The /usr/share/zoneinfo directory was selected in each case.

The test included a job to list the contents of /usr/share/zoneinfo (again symlinked to /var/db/timezone/zoneinfo). That indicated the iso3166.tab file is present:

```
1152921500312795634 lrwxr-xr-x  1 root  wheel  25 Jan  1  2020 /usr/share/zoneinfo -> /var/db/timezone/zoneinfo

/usr/share/zoneinfo:
+VERSION
Africa
America
Antarctica
Arctic
Asia
Atlantic
Australia
Brazil
CET
CST6CDT
Canada
Chile
Cuba
EET
EST
EST5EDT
Egypt
Eire
Etc
Europe
Factory
GB
GB-Eire
GMT
GMT+0
GMT-0
GMT0
Greenwich
HST
Hongkong
Iceland
Indian
Iran
Israel
Jamaica
Japan
Kwajalein
Libya
MET
MST
MST7MDT
Mexico
NZ
NZ-CHAT
Navajo
PRC
PST8PDT
Pacific
Poland
Portugal
ROC
ROK
Singapore
Turkey
UCT
US
UTC
Universal
W-SU
WET
Zulu
iso3166.tab
leapseconds
posixrules
zone.tab
```

The /usr/share/zoneinfo.default directory also existed with identical top level file and directory names as /usr/share/zoneinfo.

I've not seen any similar issues reported with MacOS.

I'm therefore going to close this issue for now.
