### ISSUE TITLE
tzinfo/datetime_with_offset (LoadError)

### ISSUE THREAD

**Issue by ayyanambalam** [tzinfo/tzinfo#132]
C:/Ruby/lib/ruby/gems/3.1.0/gems/tzinfo-2.0.4/lib/tzinfo.rb:22:in `require_relative': cannot load such file -- C:/Ruby/lib/ruby/gems/3.1.0/gems/tzinfo-2.0.4/lib/tzinfo/datetime_with_offset (LoadError)

**Comment by philr** [comment]
I've checked with a [RubyInstaller](https://rubyinstaller.org) build of Ruby 3.1.0 x64 on Windows 10 and requiring tzinfo works fine for me:

```
> ruby -v
ruby 3.1.0p0 (2021-12-25 revision fb4df44d16) [i386-mingw32]

> gem install tzinfo -v2.0.4
Fetching tzinfo-2.0.4.gem
Successfully installed tzinfo-2.0.4
Parsing documentation for tzinfo-2.0.4
Installing ri documentation for tzinfo-2.0.4
Done installing documentation for tzinfo after 2 seconds
1 gem installed

> ruby -e "gem 'tzinfo', '2.0.4'; require 'tzinfo'; puts TZInfo::VERSION"
2.0.4
```

Your error seems to be a problem loading the datetime_with_offset.rb file. Does C:\Ruby\lib\ruby\gems\3.1.0\gems\tzinfo-2.0.4\lib\tzinfo\datetime_with_offset.rb exist? Does the user running the ruby process have access to read the file?
