### ISSUE TITLE
Testing with system tzdata

### ISSUE THREAD

**Issue by voxik** [tzinfo/tzinfo#141]
Working on update of tzinfo for Fedora, I just thought that it could possible make a sense to test against system tzdata, therefore I did:

~~~
$ sed -i '/zoneinfo_path/ s|= .*|= "/usr/share/zoneinfo"|' test/ts_all_zoneinfo.rb

$ ruby test/ts_all_zoneinfo.rb
~~~

Unfortunately, this fails:

~~~
  1) Failure:
TCTimezoneMelbourne#test_1942 [/builddir/build/BUILD/test/tc_timezone_melbourne.rb:96]:
utc_offset.
Expected: 36000
  Actual: 39600
~~~

I assume this difference in tzdata and this is possibly part of the reason why the test suite carries around its own copy. Therefore I just wanted to check, if testing against system tzdata is something which would make sense also from upstream POV. If I should eventually keep reporting such issues and they are going to be addressed.

BTW if this is something of interest, it would be helpful if the `zoneinfo_path` coiuld be modified via env variable.

**Comment by philr** [comment]
The fixtures included in the test suite are based on version 2020d of the IANA Time Zone Database. The tests have hardcoded expectations of what the fixtures will return.

[Version 2020e](https://mm.icann.org/pipermail/tz-announce/2020-December/000063.html) made [changes to historical Australian transitions](https://github.com/eggert/tz/commit/1aca4cad3692063cd5cb571883ccf6d04b3c2991). That includes Australia/Melbourne transitions in 1942 that cause the TCTimezoneMelbourne#test_1942 test to fail when run against newer data.

I don't think there's any real value in keeping the fixtures up to date with new data releases. The only time it needs to be done is if there is a new file format that would benefit from being tested. Even then, new files could be generated using the 2020d data to avoid having to change the hardcoded expectations.

The fact that the test fixtures happen to share names with actual time zones should really be taken as a coincidence - they're just sample data.

I think it would also be unlikely that the tests would be run on a system where the version of tzinfo being tested (with the expected data hardcoded) happened to match the version of the installed zoneinfo files. Unless there's been a recent tzinfo release, it's likely that the system zoneinfo files would be newer.

A more meaningful test would be to compare the output of tzinfo with something else that uses the zoneinfo files as a reference. tzinfo-data includes tests that do just that in [tc_definitions.rb](https://github.com/tzinfo/tzinfo-data/blob/v1.2022.3/test/tc_definitions.rb). Those tests check that the generated Ruby definition files match up with output from the zdump command. That could be adapted to compare tzinfo with the zoneinfo data source selected against output from the system zdump command, both using the system zoneinfo files.

**Comment by voxik** [comment]
> The fact that the test fixtures happen to share names with actual time zones should really be taken as a coincidence - they're just sample data.

Ah, I have not realized that the `zoneinfo` data are somehow stripped down/modified version of zoneinfo data, if I understand you comment correctly. It could have been completely different data, they are not for convenience. :+1: 

> I think it would also be unlikely that the tests would be run on a system where the version of tzinfo being tested (with the expected data hardcoded) happened to match the version of the installed zoneinfo files. Unless there's been a recent tzinfo release, it's likely that the system zoneinfo files would be newer.

Right.

> A more meaningful test would be to compare the output of tzinfo with something else that uses the zoneinfo files as a reference. tzinfo-data includes tests that do just that in [tc_definitions.rb](https://github.com/tzinfo/tzinfo-data/blob/v1.2022.3/test/tc_definitions.rb). Those tests check that the generated Ruby definition files match up with output from the zdump command. That could be adapted to compare tzinfo with the zoneinfo data source selected against output from the system zdump command, both using the system zoneinfo files.

On Fedora, we are generally happy without the tzinfo-data, so basically we don't have one reference.

Nevertheless, I think that the main takeaway is that testing the tzinfo against system zoneinfo does not make too much sense, therefore I'll keep the test non-failing or consider to remove it.

Thx a lot for the insights. Feel free to close.

**Comment by voxik** [comment]
> > Nevertheless, I think that the main takeaway is that testing the tzinfo against system zoneinfo does not make too much sense, therefore I'll keep the test non-failing or consider to remove it.
> 
> My recommendation would be to run the tests using the test fixtures (i.e. without modifying `zoneinfo_path` in `ts_all_zoneinfo.rb`).

Yes, we do this already. So we should be good. Thx :+1:
