### ISSUE TITLE
UTC time difference with Timezones

### ISSUE THREAD

**Issue by abidiqbalk** [tzinfo/tzinfo#146]
Hello,

I need to show UTC difference with each timezone as attached in the screenshot. Is this possible?
A quick help will highly be appreciated.
Thanks in advance.
![image](https://user-images.githubusercontent.com/1542924/221266549-b428ce14-d1e6-45b6-a07e-a25c6043972d.png)

**Comment by philr** [comment]
Yes, it's possible.

The [`TZInfo::Timezone.all`](https://www.rubydoc.info/gems/tzinfo/2.0.6/TZInfo%2FTimezone%2Eall) method will return an array of all the time zones. You might want to consider [`TZInfo::Timezone.all_country_zones`](https://www.rubydoc.info/gems/tzinfo/2.0.6/TZInfo%2FTimezone%2Eall_country_zones) instead for a more restricted set.

The [`TZInfo::Timezone#base_utc_offset`](https://www.rubydoc.info/gems/tzinfo/2.0.6/TZInfo%2FTimezone:base_utc_offset) method will give you the base offset from UTC for a time zone in seconds.
