### ISSUE TITLE
Latest 2023c data update on v2

### ISSUE THREAD

**Issue by kcore** [tzinfo/tzinfo#151]
Hi I was checking the releases for latest 2023 data and I confused - 
There seems to be a release dated April 10 2023 [v0.3.62](https://github.com/tzinfo/tzinfo/releases/tag/v0.3.62) which includes tzdata 2023c.
There also seems to be a older release Jan 29 2023 [v2.0.6](https://github.com/tzinfo/tzinfo/releases/tag/v2.0.6) which doesn't seem to include the latest 2023c data update.

I am unable to figure out why did a v0.X version get the update but v2.XX doesnt - I am sure I am missing something.. apologies if its obvious.. any help would be much appreciated..

**Comment by philr** [comment]
tzinfo v0 packages the time zone data as part of the gem.

tzinfo v1 and later do not include any data. It can load data either from zoneinfo files on the system, or from the tzinfo-data gem. tzinfo-data v1.2023.3 includes data from the 2023c tzdata release.

tzinfo v0.3 is occasionally updated. There's a new release of tzinfo-data for every tzdata release.

**Comment by kcore** [comment]
Okay - Thank you for the clarification - my apologies for the ignorance.
Brief background on what prompted this - Monterrey seems to have stopped DST as of December 2022. 
We are using tzinfo v2.0.6 with rails 6 and as of right now, it shows the offset as GMT-5 (considering DST) instead of GMT-6 for Monterrey.. This is what prompted me to check the updates..

Any idea what I might be missing? Thank you once again for your time

**Comment by philr** [comment]
The Rails Monterrey time zone [is defined as America/Monterrey](https://github.com/rails/rails/blob/7d949d7c81d2ec3c6d21525ebb08c85f3f174b74/activesupport/lib/active_support/values/time_zone.rb#L47C42-L47C59) in the IANA time zone database.

The change to reflect America/Monterrey no longer observing DST after 2022 was [released in version 2022f](https://mm.icann.org/pipermail/tz-announce/2022-October/000075.html) of the IANA time zone database.

If you're currently seeing GMT-5, then you must be using time zone data that's older than 2022f. If you're using the tzinfo-data gem, then check you're using [version 1.2022.6](https://github.com/tzinfo/tzinfo-data/releases/tag/v1.2022.6) or later. If you're not using the tzinfo-data gem (using the system zoneinfo files), then check for an updated time zone data package for your operating system (or switch to the tzinfo-data gem).

You can use [TZInfo::DataSource.get](https://www.rubydoc.info/gems/tzinfo/2.0.6/TZInfo%2FDataSource%2Eget) to see what data source is being used.

For example, with tzinfo-data:

```ruby
TZInfo::DataSource.get.to_s
#=> "Ruby DataSource: tzdb v2023c, tzinfo-data v1.2023.3"
TZInfo::Timezone.get('America/Monterrey').now
#=> 2023-07-28 12:12:00.779655463 -0600
```

And without tzinfo-data:

```ruby
TZInfo::DataSource.get.to_s
#=> "Zoneinfo DataSource: /usr/share/zoneinfo"
TZInfo::Timezone.get('America/Monterrey').now
#=> 2023-07-28 12:13:15.363785549 -0600
```

**Comment by kcore** [comment]
This is really helpful. Thank you @philr appreciate your time and support!
