### ISSUE TITLE
Mexico City has DST 

### ISSUE THREAD

**Issue by gaurav-mane-eptura** [tzinfo/tzinfo#152]
Currently Mexico_City is not in DST, But with TZinfo gem we are getting time as per DST. 
Please suggest/look into this issue.

**Comment by philr** [comment]
You need to update your time zone data.

The change to stop observing DST for America/Mexico_City was included in [version 2022f](https://mm.icann.org/pipermail/tz-announce/2022-October/000075.html) of the [IANA Time Zone Database](https://www.iana.org/time-zones).

TZInfo v1 and later can either use zoneinfo files from your system or the tzinfo-data gem as the source of the data. You can use [TZInfo::DataSource.get](https://www.rubydoc.info/gems/tzinfo/2.0.6/TZInfo%2FDataSource%2Eget) to see what [data source](https://www.rubydoc.info/gems/tzinfo/2.0.6/file/README.md#data-sources) tzinfo is using.

If you're using the tzinfo-data gem, then check you're using [version 1.2022.6](https://github.com/tzinfo/tzinfo-data/releases/tag/v1.2022.6) or later. If you're not using the tzinfo-data gem (using the system zoneinfo files), then check for an updated time zone data package for your operating system (or switch to the tzinfo-data gem by adding it to your Gemfile).

See also #151.
