### ISSUE TITLE
TZINFO No Source found

### ISSUE THREAD

**Issue by Tannerguo** [tzinfo/tzinfo#157]
jekyll 3.9.5 | Error:  No source of timezone data could be found.
Please refer to https://tzinfo.github.io/datasourcenotfound for help resolving this error.
C:/Ruby32-x64/lib/ruby/gems/3.2.0/gems/tzinfo-2.0.6/lib/tzinfo/data_source.rb:159:in `rescue in create_default_data_s
ource': No source of timezone data could be found. (TZInfo::DataSourceNotFound)
Please refer to https://tzinfo.github.io/datasourcenotfound for help resolving this error.

I've exhausted all stackoverflow answers and other forums and still cannot find a fix for this.
Jekyll version 3.9.5
Bundler version 2.5.6
Ruby 3.2.3 x64-mingw-ucrt
Gem version 3.5.6

**Comment by philr** [comment]
It looks like you're on Windows, so you'll need to make sure the tzinfo-data gem is installed. The error is reporting that it can't be found.

First of all try running `bundle install` from your Jekyll folder and check to see if tzinfo-data gets installed. If there are any other errors, you'll need to resolve these to get the bundle fully installed.

If tzinfo-data isn't being installed, check the `Gemfile` file in your Jekyll folder to make sure it includes a line like:

```ruby
gem "tzinfo-data"
```

If there's a `platforms` option on that line, try removing it. If the line is in a `platforms ... do ... end` block, try moving it out of the block onto a new line after the `end`.

After making changes to `Gemfile` you'll need to run `bundle update`.

**Comment by philr** [comment]
I see you've got a Gemfile in your [Tannerguo/tannerguo.github.io](https://github.com/Tannerguo/tannerguo.github.io) Jekyll project. The `Gemfile` is currently not valid. [Lines 29 to 33](https://github.com/Tannerguo/tannerguo.github.io/blob/e2a31d804af935bd1eec6d1970ec77d4fb10cce6/Gemfile#L29-L33) are currently:

```ruby
  gem install 'tzinfo-data'
  gem install 'tzinfo'
  gem install 'tzdata'
  gem install 'tz-info'
  gem 'tzinfo-data', platforms: [:x64_mingw, :mingw, :mswin]
```

`gem install` isn't valid syntax for a Gemfile. 'tzdata' and 'tz-info' aren't valid gem names. Try replacing those lines with the following:

```ruby
  gem 'tzinfo'
  gem 'tzinfo-data'
```

You've also got the wdm gem included twice on [line 19](https://github.com/Tannerguo/tannerguo.github.io/blob/e2a31d804af935bd1eec6d1970ec77d4fb10cce6/Gemfile#L19) and [line 28](https://github.com/Tannerguo/tannerguo.github.io/blob/e2a31d804af935bd1eec6d1970ec77d4fb10cce6/Gemfile#L28). You'll need to remove one of those lines.

After changing `Gemfile`, run `bundle update` and it should install all the dependencies.
