### ISSUE TITLE
"Africa/Adibdjan" in README.md

### ISSUE THREAD

**Issue by slimdave** [tzinfo/tzinfo#160]
Just to say that "Africa/Adibdjan", quoted as the result of:
```
identifiers = TZInfo::Timezone.all_identifiers
# => ["Africa/Adibdjan", "Africa/Accra", ..., "Zulu"]
```
... doesn't exist. It's "Africa/Abidjan".

**Comment by philr** [comment]
Thanks for the report. I've fixed the spelling.
