### ISSUE TITLE
Add alias for "Asia/New_Delhi" pointing to "Asia/Kolkata"

### ISSUE THREAD

**Issue by jaeyoung-heo-ringle** [tzinfo/tzinfo#161]
### Request
Please add an alias for the timezone `Asia/New_Delhi` that points to `Asia/Kolkata`.

### Background
While `Asia/Kolkata` is the correct IANA timezone identifier for the Indian Standard Time (IST), many users and developers mistakenly refer to `Asia/New_Delhi` due to its association with India's capital. Adding this alias would improve usability and prevent confusion for users who are unaware of the official naming conventions.

### Example Use Case
```ruby
TZInfo::Timezone.get('Asia/New_Delhi') # Should resolve to the same as 'Asia/Kolkata'

**Comment by philr** [comment]
Time zone identifiers used by TZInfo are sourced from the [IANA Time Zone Database](https://www.iana.org/time-zones) without modification.

Requests for changes to the database should be made on the Time Zone Database [mailing list](https://lists.iana.org/postorius/lists/tz.iana.org/).
