### ISSUE TITLE
`transition': failed to allocate memory (NoMemoryError)

### ISSUE THREAD

**Issue by jonatasdlp** [tzinfo/tzinfo#30]
Hi,

When i'm run the local server (webrick or puma), the following error occurs. 
/my_home/.rvm/gems/ruby-2.1.3/gems/tzinfo-1.1.0/lib/tzinfo/transition_data_timezone_info.rb:79:in `transition ': failed to allocate memory (NoMemoryError)

This error occurs using another ruby version (2.0.0, 2.1.2).

Solution?

**Comment by Nowaker** [comment]
... or you're simply using an outdated version of library that depends on tzinfo. Like Rails 4.1.0 - then update Rails to 4.1.9.

**Comment by philr** [comment]
@Nowaker Both Rails [v4.1.0](https://github.com/rails/rails/blob/v4.1.0/activesupport/activesupport.gemspec) and [v4.1.9](https://github.com/rails/rails/blob/v4.1.9/activesupport/activesupport.gemspec) have the same dependency on the tzinfo gem (`~> 1.1`).

Running `gem update` on a Rails v4.1.0 project would have been enough to install a version of TZInfo with the fix.

**Comment by Nowaker** [comment]
@philr Yeah. Deleting the comment.
