### ISSUE TITLE
Daylight saving not being considered

### ISSUE THREAD

**Issue by brauliobo** [tzinfo/tzinfo#35]
On the system (ubuntu 14.10) I get:
```
~/P/n/blogoosfero git:blogoosfero ❯❯❯ TZ='America/Bahia' date                                                                                                                          
Ter Jan 13 13:38:27 BRT 2015
~/P/n/blogoosfero git:blogoosfero ❯❯❯ TZ='America/Sao_Paulo' date                                                                                                                       
Ter Jan 13 14:38:32 BRST 2015
```
And on Rails console I get:
```
irb(main):002:0> Time.zone = 'America/Bahia'
=> "America/Bahia"
irb(main):003:0> Time.zone.formatted_offset
=> "-03:00"
irb(main):004:0> Time.zone = 'America/Sao_Paulo'
=> "America/Sao_Paulo"
irb(main):005:0> Time.zone.formatted_offset
=> "-03:00"
```

I'm using rails 3.2.21 and tzinfo 0.3.42 (as required by activerecord 3.2.21)

**Comment by philr** [comment]
According to the [Rails source code](https://github.com/rails/rails/blob/ba910d76509158d531c637c4ab777beb8b20e53d/activesupport/lib/active_support/values/time_zone.rb#L219), the `ActiveSupport::TimeZone#formatted_offset` method returns the difference between UTC and the standard time for the zone. It will not take daylight savings time into account.

If you want to find the current offset, you can use the [`ActiveSupport::TimeWithZone#formatted_offset`](https://github.com/rails/rails/blob/d39d878d2b250636256ecf54473d365ffb62eb6d/activesupport/lib/active_support/time_with_zone.rb#L97) method instead:

```ruby
  > Time.zone = 'America/Bahia'
 => "America/Bahia" 
  > Time.zone.now.formatted_offset
 => "-03:00" 
  > Time.zone = 'America/Sao_Paulo'
 => "America/Sao_Paulo" 
  > Time.zone.now.formatted_offset
 => "-02:00" 
```

**Comment by brauliobo** [comment]
thanks @philr !
