### ISSUE TITLE
TZInfo::Timezone.get('America/New_York').utc_to_local(nil) = -18000

### ISSUE THREAD

**Issue by aug-riedinger** [tzinfo/tzinfo#39]
I would expect:

```
TZInfo::Timezone.get('America/New_York').utc_to_local(nil) # to equal nil
```

Because the time difference of nothing is nothing.

Used in code, it goes like:

```
TZInfo::Timezone.get('America/New_York').utc_to_local(Object.updated_at) # Object.updated_at can be nil
```

which consequently requires a `if Object.updated_at` appended, which is IMHO less elegant.

**Comment by philr** [comment]
Sorry for the delay in responding to this. 

I've decided to make TZInfo raise an exception when passed a `nil` time (this is now implemented on the master branch). On balance, I think it is better to be explicit about handling `nil` values.

As for keeping the code elegant, you could add a method to the `Time` class in your project and then use it along with the safe navigation (`&.`) operator. For example:

```ruby
class Time
  def to_new_york
    TZInfo::Timezone.get('America/New_York').utc_to_local(self)
  end
end

object.updated_at&.to_new_york
```
