### ISSUE TITLE
Include 2016a data

### ISSUE THREAD

**Issue by vemv** [tzinfo/tzinfo#43]
Hi there!

2016a was released on 2016-01-26. https://www.iana.org/time-zones

This gem should be updated to include it, right?

Cheers - Victor

**Comment by philr** [comment]
The Time Zone database release was only [announced](http://mm.icann.org/pipermail/tz-announce/2016-January/000035.html) 17 hours ago (on 2016-01-28).

There will be a new version of the tzinfo-data gem for every release of the Time Zone database.

New versions of the old tzinfo 0.3 branch will be released occasionally if there are significant data changes. However, I'm planning to drop support for 0.3 once there are no longer any supported Ruby on Rails releases that rely on it (i.e. once support for Rails 3.2 is withdrawn).
