### ISSUE TITLE
Switch from ThreadSafe::Cache to Concurrent::Map

### ISSUE THREAD

**Issue by philr** [tzinfo/tzinfo#46]
See the discussion on #45.

The thread_safe gem has been merged into concurrent-ruby and thread_safe is being deprecated.

The code should be changed to use `Concurrent::Map` from concurrent-ruby instead of `ThreadSafe::Cache` (`Concurrent::Map` is a carbon copy of `ThreadSafe::Cache`).

tzinfo currently has a `required_ruby_version` of `>= 1.8.7`. This would need changing to `>= 1.9.3` to match concurrent-ruby. Some of the code to support Ruby 1.8 in and around [`ruby_core_support.rb`](https://github.com/tzinfo/tzinfo/blob/61fdd4359117e9a406c546bdc044a3e41faaa5d7/lib/tzinfo/ruby_core_support.rb) could also then be dropped.

**Comment by kares** [comment]
Hello Phil, noticed *thread_safe* is still being pulled in (along side concurrent-ruby in Rails 5.x)
since there's work done to get rid off it on master, for some time, was wondering if you plan on releasing?
assuming you do not want it in a 1.2 minor release due backwards compatibility.

**Comment by philr** [comment]
@kares My intention is to make a 2.0.0 release from master sometime in the next few weeks.

This won't immediately help with Rails 5.x though - [changes will be needed to work with tzinfo v2](https://github.com/philr/rails/tree/tzinfo_v2).

I could possibly look into creating a 1.3.0 release too that includes the concurrent-ruby change as well as the required increase to the `required_ruby_version`. This would be usable by Rails 5.x (activesupport depends on `~> 1.1`).
