### ISSUE TITLE
High memory consumption

### ISSUE THREAD

**Issue by psienko** [tzinfo/tzinfo#54]
I have noticed that the tzinfo gem generate many string objects.

Links to problematic lines:
* https://github.com/tzinfo/tzinfo/blob/master/lib/tzinfo/zoneinfo_timezone_info.rb#L131
* https://github.com/tzinfo/tzinfo/blob/master/lib/tzinfo/zoneinfo_timezone_info.rb#L137
* https://github.com/tzinfo/tzinfo/blob/master/lib/tzinfo/zoneinfo_timezone_info.rb#L143
* https://github.com/tzinfo/tzinfo/blob/master/lib/tzinfo/zoneinfo_timezone_info.rb#L150

Maybe good idea will be using freezing strings (e.g. 'NN'.freeze) or storing strings as constants.

Below are memory profiling results for one of request in my application

###### Results before freezing strings:

allocated memory by gem [bytes] | allocated objects by gem | allocated memory by class [bytes] | allocated objects by class
--------------------------------- | --------------------------------| -----------------------------------|---------------------------------|
    5519372  tzinfo-1.2.2 |     181142  tzinfo-1.2.2 |   29220995  String |     324131  String

###### Results after freezing strings:
allocated memory by gem [bytes] | allocated objects by gem | allocated memory by class [bytes] | allocated objects by class
--------------------------------- | --------------------------------| -----------------------------------|---------------------------------|
32160  tzinfo-1.2.2 |     1044  tzinfo-1.2.2 |   27375064  String |     263417  String

**Comment by philr** [comment]
Thank you for reporting this. A change to freeze the strings you have identified has been merged as part of #57.

**Comment by philr** [comment]
The fix for this issue has now been released in [version 1.2.3](https://github.com/tzinfo/tzinfo/releases/tag/v1.2.3).
