### ISSUE TITLE
Timezone is not correct

### ISSUE THREAD

**Issue by rotem443** [tzinfo/tzinfo#55]
I'm trying to get the offset from the UTC time at Israel timezone:

TZInfo::Timezone.get('Israel').current_period.utc_offset / (60*60)

The result is 2 hours when 3 hours is expected (http://www.timeanddate.com/time/zone/israel/jerusalem)

**Comment by philr** [comment]
`utc_offset` gives the base offset of the time zone (not taking daylight savings time into account). For the total offset including daylight savings time, use [`utc_total_offset`](http://www.rubydoc.info/gems/tzinfo/TZInfo/TimezonePeriod#utc_total_offset-instance_method) instead:

```ruby
TZInfo::Timezone.get('Israel').current_period.utc_total_offset / (60*60)
```
