### ISSUE TITLE
Turkey decided to use summer time all year round

### ISSUE THREAD

**Issue by dabrorius** [tzinfo/tzinfo#59]
Hello,
it seems that Turkey decided do [stop moving their clock](https://www.theguardian.com/world/2016/sep/08/turkey-to-stay-on-summer-time-all-year-round) in the winter. It seems to be causing some issues for us.
Are there already plans to update TZInfo to accommodate this?
I'm willing to invest some time in this too, but just wanted to check in with the core team first.

**Comment by philr** [comment]
TZInfo is already updated.

TZInfo v1+ uses either your system time zone information or the tzinfo-data gem for its data (see the [Data Sources](http://www.rubydoc.info/gems/tzinfo/file/README.md#Data_Sources) section of the Readme).

The tzinfo-data gem and older v0.3.x versions of tzinfo both package the time zone data published in the [IANA Time Zone Database](https://www.iana.org/time-zones).

The recent changes for Turkey are included in the [2016h release](http://mm.icann.org/pipermail/tz-announce/2016-September/000041.html) of the IANA Time Zone Database.

The 2016h release of the time zone data is included in tzinfo-data [v1.2016.7](https://github.com/tzinfo/tzinfo-data/releases/tag/v1.2016.7) and tzinfo [v0.3.52](https://github.com/tzinfo/tzinfo/releases/tag/v0.3.52).

If you're using TZInfo v1+, then you'll either need to update your system time zone data or install/update to the latest version of tzinfo-data.

If you're using TZInfo v0.3.x, then you'll need to update to version 0.3.52.

**Comment by dabrorius** [comment]
Got it! Thanks a lot for the detailed information.
