### ISSUE TITLE
Backport #47 to a new minor version

### ISSUE THREAD

**Issue by kalleth** [tzinfo/tzinfo#65]
To support ruby 2.4.0 in rails 4.2 (see my backport https://github.com/rails/rails/pull/27905) and completely remove the deprecation warnings for Fixnum caused by the unsupported `thread_safe` gem, it'd be great if you could release a `1.2.3` version containing just PR #47. That way I can upgrade that entirely and then no deprecation warnings happen on any old rails apps running 4.2 :)

Please let me know if I can help at all with this!

**Comment by philr** [comment]
There's a merged pull request (ruby-concurrency/thread_safe#29) to fix the Ruby 2.4 warnings in the thread_safe gem.

A new release of thread_safe that fixes the warnings sounds like a better solution than releasing a minor update to tzinfo that changes a dependency.
