### ISSUE TITLE
TimeZone#strftime doesn't give correct local offset

### ISSUE THREAD

**Issue by mj1856** [tzinfo/tzinfo#67]
`TimeZone#strftime` replaces `%Z` with the correct local abbreviation, but it leaves `%z` at `+0000` instead of the correct local wall-time offset.  Same for `%:z`, `%::z` and `%:::z`.

**Comment by philr** [comment]
Support for returning the correct offset for `%z` (and associated formats) in `Timezone#strftime` has already been implemented. It will be included in the next TZInfo release.

**Comment by philr** [comment]
[Version 1.2.3](https://github.com/tzinfo/tzinfo/releases/tag/v1.2.3) has now been released. This adds support for returning the correct offset for `%z`.
