### ISSUE TITLE
Timezone format for Bogota is wrong

### ISSUE THREAD

**Issue by cpovey** [tzinfo/tzinfo#68]
It appears that the 3-letter format string for the "Bogota" timezone has changed from "COT" to "-05" in the latest version. All other timezones tested appear correct. I dug into the latest database (https://www.iana.org/time-zones) and searched for in the `southamerica` file and could not find "COT" anywhere. Here is the entry for Bogota: 

```
# Colombia

# Milne gives 4:56:16.4 for Bogotá time in 1899; round to nearest.  He writes,
# "A variation of fifteen minutes in the public clocks of Bogota is not rare."

# Rule	NAME	FROM	TO	TYPE	IN	ON	AT	SAVE	LETTER/S
Rule	CO	1992	only	-	May	 3	0:00	1:00	S
Rule	CO	1993	only	-	Apr	 4	0:00	0	-
# Zone	NAME		GMTOFF	RULES	FORMAT	[UNTIL]
Zone	America/Bogota	-4:56:16 -	LMT	1884 Mar 13
			-4:56:16 -	BMT	1914 Nov 23 # Bogotá Mean Time
			-5:00	CO	-05/-04
```

Other timezones have the correct 3-letter abbreviation in the place where `-05/-04` is. Does anyone know how to submit this as a bug?

**Comment by philr** [comment]
Issues with the IANA Time Zone Database should be discussed on the [tz mailing list](https://mm.icann.org/mailman/listinfo/tz).

TZInfo just returns information from the database unchanged.

The abbreviation for America/Bogota was changed from COT to -05 in version [2017a](https://mm.icann.org/pipermail/tz-announce/2017-February/000045.html) of the Time Zone Database (commit eggert/tz@c9e6ef07cc6f1062ddd032c96c5172f403c0058f):

> Switch to numeric time zone abbreviations for South America, as part of the ongoing project of removing invented abbreviations.

It looks like "COT" was considered to be a made up abbreviation (COlumbia Time) that is not used locally and was therefore changed to a numeric value. If you think this is an error, then I'd suggest opening a discussion on the tz mailing list.
