### ISSUE TITLE
Wrong UTC Offset for "Etc/GMT-12"

### ISSUE THREAD

**Issue by mrj** [tzinfo/tzinfo#69]
```
require 'tzinfo'
TZInfo::Timezone.get('Etc/GMT-12').current_period

=> #<TZInfo::TimezonePeriod: nil,nil,#<TZInfo::TimezoneOffset: 43200,0,+12>>>
```
GMT-12 is a useful "Anywhere on Earth" zone.

**Comment by philr** [comment]
An offset of +12 hours is the correct result for the Etc/GMT-12 zone.

TZInfo uses the data from the [IANA Time Zone database](https://www.iana.org/time-zones). This defines the Etc/GMT[+-]n zones in a POSIX-compliant (but unexpected) manner. From the [etcetera file](https://github.com/eggert/tz/blob/5659c5322976ea171e6a5afe14e9bc8172a51e24/etcetera#L36) in the database:

> Be consistent with POSIX TZ settings in the Zone names even though this is the opposite of what many people expect. POSIX has positive signs west of Greenwich, but many people expect positive signs east of Greenwich.  For example, TZ='Etc/GMT+4' uses the abbreviation "-04" and corresponds to 4 hours behind UT (i.e. west of Greenwich) even though many people would expect it to mean 4 hours ahead of UT (i.e. east of Greenwich).

**Comment by mrj** [comment]
OK. I've now got to work out why this zone is coming up in ActiveSupport::TimeZone as GMT+12, adjacent to Auckland, rather than at the top before American Samoa.
