### ISSUE TITLE
-02 abbreviation for 'Atlantic/South_Georgia'

### ISSUE THREAD

**Issue by curtp** [tzinfo/tzinfo#82]
Hello,

I think this may be a configuration issue between our development and our production environments, but I'm not able to track it down.

We have a user who selected the 'Atlantic/South_Georgia' timezone.  When the time zone is displayed, it is showing -02 for the abbreviation instead of GST which is what I'm getting in my development environment.

Here is the output from both environments showing the difference.

Local:
tz = TZInfo::Timezone.get('Atlantic/South_Georgia')
 => #<TZInfo::DataTimezone: Atlantic/South_Georgia> 
tz.current_period
 => #<TZInfo::TimezonePeriod: #<TZInfo::TimezoneTransitionDefinition: #<TZInfo::TimeOrDateTime: -2524512832>,#<TZInfo::TimezoneOffset: -7200,0,**GST**>>,nil> 
tz.current_period.abbreviation
 => :GST

Production:
tz = TZInfo::Timezone.get('Atlantic/South_Georgia')
 => #<TZInfo::DataTimezone: Atlantic/South_Georgia> 
tz.current_period
 => #<TZInfo::TimezonePeriod: #<TZInfo::TimezoneTransitionDefinition: #<TZInfo::TimeOrDateTime: -2524512832>,#<TZInfo::TimezoneOffset: -7200,0,**-02**>>,nil> 
tz.current_period.abbreviation
 => :"-02"

Any pointers on where I can look next?

**Comment by curtp** [comment]
Sorry for close/reopen.  I think I've tracked it down to a difference between the content of /usr/share/zoneinfo/Atlantic/South_Georgia

Going to look into using the TZInfo::Data source instead of OS

**Comment by raelgc** [comment]
@curtp I'm facing a similar issue, where the abbreviation for the timezone is returned as integer instead of a string with the correct abbreviation (in my case, I want to see `BRT` for `America/Sao_Paulo` but I'm getting only `-03`).

How you forced to use TZInfo::Data? Just including `tzinfo` and `tzinfo-data` gems in bundler?

**Comment by curtp** [comment]
Unfortunately, we never did get it to work properly.  It is still working off of the /usr/share/zoneinfo files and displaying whatever is contained within it.
