### ISSUE TITLE
undefined method `to_local' for #<TZInfo::DataTimezone: America/New_York>

### ISSUE THREAD

**Issue by HCLarsen** [tzinfo/tzinfo#84]
Despite your code showing a to_local method, and your README showing how to use it, it seems impossible to call this method on a TimeZone object.

**Comment by philr** [comment]
It sounds like you're probably running the latest gem release, but reading the code and README file on the master branch.

The master branch contains changes that have not yet been released. One of these changes was the addition of a `to_local` method to `TZInfo::Timezone`.

The code and README for the latest gem release can be found in git [tagged as v1.2.5](https://github.com/tzinfo/tzinfo/tree/v1.2.5). The documentation for this release is [available on RubyDoc.info](http://www.rubydoc.info/gems/tzinfo/1.2.5).

**Comment by HCLarsen** [comment]
Problem with that is that the documentation on RubyDoc.info is incomplete. It contains no listing for the TZInfo::DataTimezone class.

**Comment by HCLarsen** [comment]
Good to know. Thank you.

**Comment by Cuurjol** [comment]
Nowadays the issue is not solved. Please, fix it!

**Comment by AlexWayfer** [comment]
> 584 commits to master since this release

Is there a new release planned?

**Comment by philr** [comment]
Yes, there will be a 2.0.0 release from master sometime soon.
