### ISSUE TITLE
Missing Timezone America/Punta_Arenas

### ISSUE THREAD

**Issue by silva96** [tzinfo/tzinfo#87]
Since last year, Punta Arenas has a different timezone than Chile, please refer to this link

https://mm.icann.org/pipermail/tz-announce/2017-February/000045.html

Can you add it?

Regards

**Comment by philr** [comment]
TZInfo is already updated.

TZInfo v1.0.0 and later uses either your system time zone information or the tzinfo-data gem for its data (see the [Data Sources](https://www.rubydoc.info/gems/tzinfo/1.2.5/file/README.md) section of the Readme).

The tzinfo-data gem and older v0.3.x versions of tzinfo both package the time zone data published in the [IANA Time Zone Database](https://www.iana.org/time-zones).

The America/Punta_Arenas zone is included in tzinfo-data [v1.2017.1](https://github.com/tzinfo/tzinfo-data/releases/tag/v1.2017.1) and tzinfo [v0.3.53](https://github.com/tzinfo/tzinfo/releases/tag/v0.3.53).

If you're using TZInfo v1.0.0 or later, then you'll either need to update your system time zone data or install/update to at least v1.2017.1 of tzinfo-data.

If you're using TZInfo v0.3.x, then you'll need to update to at least version 0.3.53.

**Comment by silva96** [comment]
Thank you for clarification on how it works, I tested it on mac and ubuntu and it works correctly, sorry for the misunderstood, please close this issue.
