### ISSUE TITLE
Compatibility with 'vanguard' data format including negative DST offsets.

### ISSUE THREAD

**Issue by voxik** [tzinfo/tzinfo#88]
In Fedora, there was recently announced this change proposal [[1]]:

> As of tzdata-2018e, the upstream will now default to using the 'vanguard' data format including negative DST offsets.

Because we are using the system tzdata to provide the time zone information, I wonder if the tzinfo is compatible with this updated format. Since the tzinfo-data was already updated to tzdata-2018e, I assume that the answer is "yes, tzinfo supports the new format just fine", but I'd like to double check.

Thx

[1]: https://fedoraproject.org/wiki/Changes/TZDATA-VANGUARD

**Comment by philr** [comment]
Yes, tzinfo supports the vanguard format introduced in tzdata 2018d that became the main format in 2018e.

Conversions to and from local time will be accurate with any release supporting system zoneinfo files.

I would recommend using the latest [v1.2.5](https://github.com/tzinfo/tzinfo/releases/tag/v1.2.5) release though. This includes a fix to allow negative daylight savings time offsets to be derived from zoneinfo files. This sets the [`TimezonePeriod#std_offset`](https://www.rubydoc.info/gems/tzinfo/1.2.5/TZInfo/TimezonePeriod#std_offset-instance_method) and [`TimezonePeriod#utc_offset`](https://www.rubydoc.info/gems/tzinfo/1.2.5/TZInfo/TimezonePeriod#utc_offset-instance_method) attributes correctly when loading zoneinfo time zones that contain negative DST offsets.

**Comment by voxik** [comment]
@philr Thanks a lot for details
